#!/usr/bin/env bash
if [[ "$0" != "${BASH_SOURCE}" ]]; then
  eval "$(govenv sh-activate --verbose "$@" || true)"
else
  echo "govenv-virtualenv: activate must be sourced. Run 'source activate envname' instead of 'activate envname'" 1>&2
  false
fi
